### ISSUE TITLE
RStudio build leaves 'figure' in the vignettes folder

### ISSUE THREAD

**Issue by mkborregaard** [txm676/gambin#7]
When I try to get the package ready for cran, as Rstudio puts a 'figure' folder in the 'vignettes' directory. The CRAN people could not help me get rid of this, but they will not take the package with this subfolder. Using the tar function to unpack the package, delete the folder manually and re-tar the package introduces other hidden files (.DS_Store), and I cannot see how to avoid this.

@csgillespie, this seems to be created by knitr - do you know a fix?

**Comment by csgillespie** [comment]
To ignore files from the CRAN build edit the .Rbuildignore file (the current git version does not contain this folder.)

Since it passes travis  it should (but not always) pass the CRAN. Another place to try is http://win-builder.r-project.org/upload.aspx (for info, I just uploaded the tar.gz file so you'll get an email shortly).

I always upload to winbuilder before CRAN.

**Comment by mkborregaard** [comment]
No, the folder does not exist (so adding it to the .Rbuildignore file does nothing) - but it is created by the build script. 
The package does not pass CRAN, and Kurt Hornik can't help get it to pass. But it does pass the winbuilder check with no issues. It sometimes passes my desktop `CHECK --as-cran` , sometimes fails with the same NOTE:
```
* checking files in ‘vignettes’ ... NOTE
The following directory looks like a leftover from 'knitr':
  ‘figure’
Please remove from your package.
```
So it must be something that is created by knitr during the build.
